# Generated by Django 3.0.8 on 2020-11-23 06:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title:')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title:')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrption', models.TextField(verbose_name='Description:')),
                ('icon', models.CharField(max_length=30, verbose_name='Icon name:')),
            ],
        ),
        migrations.CreateModel(
            name='VideocastCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title:')),
            ],
        ),
        migrations.CreateModel(
            name='Videocast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title:')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug:')),
                ('thumbnail', models.ImageField(upload_to='content/video/thumbnail/', verbose_name='Thumbnail:')),
                ('publish', models.BooleanField(default=True, help_text='Will this video be published?', verbose_name='Publish:')),
                ('video', models.CharField(max_length=256, verbose_name='Video link:')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ManyToManyField(to='blog.VideocastCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title:')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug:')),
                ('thumbnail', models.ImageField(upload_to='content/podcast/thumbnail/', verbose_name='Thumbnail:')),
                ('publish', models.BooleanField(default=True, help_text='Will this audio be punlished?', verbose_name='Publish:')),
                ('audio', models.FileField(upload_to='content/podcast/audio/', verbose_name='Audio:')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ManyToManyField(to='blog.PodcastCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title:')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug:')),
                ('thumbnail', models.ImageField(upload_to='content/blog/thumbnail/', verbose_name='Thumbnail:')),
                ('publish', models.BooleanField(default=True, help_text='Will this post be published?', verbose_name='Publish:')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ManyToManyField(to='blog.BlogCategory')),
            ],
        ),
    ]
